<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class ProductoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $datos = [
            array( 
                'nombre' =>  "Gaseosa INCA KOLA 500ml",
                'precio' => 2.90,
                'imagen' => "bebida_01",
                'categoria_id' => 1,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Agua Mineral CIELO sin gas Cielo 2.5 L",
                'precio' => 1.50,
                'imagen' => "bebida_02",
                'categoria_id' => 1,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Gaseosa COCA COLA 500 mL",
                'precio' => 2.90,
                'imagen' => "bebida_03",
                'categoria_id' => 1,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Bebida Tampico Sabor Naranja 500 mL",
                'precio' => 1.80,
                'imagen' => "bebida_04",
                'categoria_id' => 1,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Bebida Frugos del Valle Fresh 500 mL",
                'precio' => 1.80,
                'imagen' => "bebida_05",
                'categoria_id' => 1,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Bebida Cifrut Sabor Naranja 3 L",
                'precio' => 5.50,
                'imagen' => "bebida_06",
                'categoria_id' => 1,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "GLORIA YOGURT GRIEGO BOTELLA 950GR C MIEL",
                'precio' => 11.90,
                'imagen' => "lácteos_01",
                'categoria_id' => 2,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "GLORIA YOGURT PAR DES 1.7KG FRESA",
                'precio' => 10.80,
                'imagen' => "lácteos_02",
                'categoria_id' => 2,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Tri Pack de Leche Gloria de 900 mL",
                'precio' => 15.20,
                'imagen' => "lácteos_03",
                'categoria_id' => 2,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Queso fundido Laive",
                'precio' => 12.90,
                'imagen' => "lácteos_04",
                'categoria_id' => 2,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "QUESO MOZARELLA LAIVE X 180 GR",
                'precio' => 10.50,
                'imagen' => "lácteos_05",
                'categoria_id' => 2,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Helado Peziduri Tricolor Donofrio",
                'precio' => 12.35,
                'imagen' => "congelados_01",
                'categoria_id' => 3,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Helado sublime chocolate con maní pote de 900 mL",
                'precio' => 20.90,
                'imagen' => "congelados_02",
                'categoria_id' => 3,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "NUGGET DE POLLO S.FNDO BOLSA x 10 UN",
                'precio' => 4.90,
                'imagen' => "congelados_03",
                'categoria_id' => 3,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Tortillas Rapiditas Clásicas Bimbo 310 g",
                'precio' => 7.50,
                'imagen' => "congelados_04",
                'categoria_id' => 3,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Mermelada de fresa Gloria de 1 kg",
                'precio' => 13.50,
                'imagen' => "congelados_05",
                'categoria_id' => 3,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Papas Lay's Clásicas 210g",
                'precio' => 8.50,
                'imagen' => "snacks_01",
                'categoria_id' => 4,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Chizito Fiesta Queso 190g",
                'precio' => 6.60,
                'imagen' => "snacks_02",
                'categoria_id' => 4,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Snack Piqueo Snax 200g",
                'precio' => 9.70,
                'imagen' => "snacks_03",
                'categoria_id' => 4,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Galleta Morochas Nestle Vainilla Cubierta de Chocolate 6 Unidades",
                'precio' => 4.80,
                'imagen' => "snacks_04",
                'categoria_id' => 4,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Galleta Pícaras con Cubierta Sabor Chocolate 40 g",
                'precio' => 4.90,
                'imagen' => "snacks_05",
                'categoria_id' => 4,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "JAMON DEL PAIS X KG",
                'precio' => 65.00,
                'imagen' => "embutidos_01",
                'categoria_id' => 5,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "TABLA PIQUEO TRADICIONAL",
                'precio' => 18.90,
                'imagen' => "embutidos_02",
                'categoria_id' => 5,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Chorizo Parrillero Fresco San Fernando 400g",
                'precio' => 15.90,
                'imagen' => "embutidos_03",
                'categoria_id' => 5,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Salchicha de pollo San Fernando 500 g",
                'precio' => 9.90,
                'imagen' => "embutidos_04",
                'categoria_id' => 5,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Lomo Embuchado España e Hijos 100g",
                'precio' => 14.90,
                'imagen' => "embutidos_05",
                'categoria_id' => 5,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Paño multiusos Scotch Brite",
                'precio' => 11.50,
                'imagen' => "limpieza_01",
                'categoria_id' => 6,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Lejía Clorox Flores de Lavanda 2 Kg",
                'precio' => 6.90,
                'imagen' => "limpieza_02",
                'categoria_id' => 6,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Ambientador con aroma a manzana y canela",
                'precio' => 10.10,
                'imagen' => "limpieza_03",
                'categoria_id' => 6,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Cera en pasta amarilla",
                'precio' => 8.50,
                'imagen' => "limpieza_04",
                'categoria_id' => 6,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Detergente en polvo Opal Ultra Anti Mancha Floral en bolsa de 2.4 kg",
                'precio' => 26.90,
                'imagen' => "limpieza_05",
                'categoria_id' => 6,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
        ];
        DB::table('productos')->insert($datos);
    }
}
